### ISSUE TITLE
Is this libary maintained?

### ISSUE THREAD

**Issue by HarrySarson** [infusion/Complex.js#19]
There are PR's which have been open for about 4 months without any feedback and the last change to `complex.js` was 8 months ago.

I was wondering if there are any plans to implement the fixes to this libary (especially the infinite value behaviour which is affecting mathjs) and release a new version to npm. Complex.js is getting 300,000+ downloads a month so it is definately worth making these fixes.

If you do not have the time to work on Complex.js currently I would be very happy to take over temporarily until you get more time.

**Comment by infusion** [comment]
Harry, thanks for reaching out. The library is of course still active. Sorry for not answering properly in the last time, I am a bit busy atm. In two weeks I have holidays and want to work on the PRs/bug tickets of my OSS projects, including infinity support of complex.js.
