### ISSUE TITLE
make EPSILON customizable

### ISSUE THREAD

**Issue by josdejong** [infusion/Complex.js#2]
It would be nice if `EPSILON` would be customizable. Could be via some "official" option, or simply by exposing it in the `Complex.prototype` so you can override it.

**Comment by infusion** [comment]
Good catch. I tend to adding it not on the prototype but as a static variable `Complex.EPSILON`, like the other exported variables `Complex.I` and so on.

**Comment by josdejong** [comment]
Sounds good.

**Comment by infusion** [comment]
Okay, we can then add Complex.EPSILON = math.PRECISION (or what the name was) in Complex.js of math.js

**Comment by josdejong** [comment]
Yes indeed. The configuration option is called `epsilon` in math.js, and you can listen for changes in the config and apply epsilon to `Complex.EPSILON`. Similar to how we apply `precision` to `BigNumber`, [see code](https://github.com/josdejong/mathjs/blob/master/lib/type/bignumber/BigNumber.js#L36-L44).

**Comment by infusion** [comment]
Thanks about the notification system of math.js, this is really cool!
