### ISSUE TITLE
pow(0+0i, 1+0i) == NaN+NaNi

### ISSUE THREAD

**Issue by tlbtlbtlb** [infusion/Complex.js#26]
```
> C = require('complex-js')
> C(0,0).pow(C(1,0))
n { abs: 0, arg: NaN }
> C(0,0).pow(C(1,0)).real
NaN
> C(0,0).pow(C(1,0)).imag
NaN
```

The case of pow(0+0i, ...) needs to be handled specially, since you can't compute the angle. I think the logic should be:
```
   if (y.real === 0 && y.imag === 0) {
    return C(1, 0)
   }
   else if (x.real === 0 && x.imag === 0) {
    return C(0, 0)
  }
  else {
    ... existing logic ...
   }
```

**Comment by infusion** [comment]
You might have the wrong library. Complex-js is someone else's library. Please try mine:

```
npm i complex.js
```

or right from this repo.

Robert

**Comment by infusion** [comment]
Okay, fixed it. New release will be available in < 5min. The problem was that the hypothenuse of the complex number is zero for 0+0i and taking the log of it introduces the problem. A valid solution of Complex.ONE is possible for `re>0&&im>=0` though. Thanks, that was a good one!
