### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by josdejong** [infusion/Complex.js#3]
Is there some special reason why you use bracket notation `this["re"]` instead of dot notation`this.re` to access properties? I find the latter easier to read.

**Comment by infusion** [comment]
Yep, I like the latter also more, but I set these on all the attributes I want to keep as they are, when they run through closure compiler in advanced mode. I started to use the advanced mode for all my projects and so I rename the attributes after finishing a project to the bracket version. This is only a little tradeoff compared to the things closure compiler brings in advanced mode, like function inlining, and code rewriting in a more optical way.

**Comment by josdejong** [comment]
Ah, does closure compiler mangle the property names too?! hm, that's not nice. I didn't know that

**Comment by infusion** [comment]
Yep, closure compiler tries to minimize them (1-2 chars) if they are not getting exported. By using this explicit syntax, you can mark them as an api. It also tries to remove objects at all. For example the P object, you don't like - if the compiler sees this object has constantly 2 attributes, it will make two variables of it (I'm not sure if in the case of P this really happens, but it tries to flatten internal objects)

**Comment by josdejong** [comment]
Well, it makes sense of course - mangling internal variable names. But it's not handy debuging in this case, you want to see `re` and `im`. 

As for `P` being replaced by two variables - that actually sounds like a good idea - it's just internals and will probably improve performance :D

**Comment by infusion** [comment]
I think not performance, as the lookup mechanism of v8 is quite advanced with it's hidden classes. Closure compiler tries to optimize for gzip, meaning building a lot of similar chunks of code, which at the end benefits performance as performance in the web means loading time.
