### ISSUE TITLE
Pow function not working correctly when imaginary component is 0 and real component is negative

### ISSUE THREAD

**Issue by atinybeardedman** [infusion/Complex.js#33]
I found that if I try to square a complex number when the imaginary part is 0 and the real part is negative, the imaginary component does not remain 0. For example:
```
let example = complex(-2,0); // -2 + 0i
example.pow(2) // should be 4 + 0i, but instead yields 4 + 9.797174393178826e-16i
```
I'm using this in a recursive algorithm and so this error is getting compounded. I looked in the source code to see why this might be happening and it seems that there is an if statement that is too specific on line 462.
```
 if (b === 0 && a >= 0) {

          return new Complex(Math.pow(a, z['re']), 0);
}
```
I believe this shouldn't be filtering out the case if the real number is negative. If we are squaring a complex number that has no imaginary component, I should just square the real component regardless of its sign. So I believe it should just read `b===0` with no and clause.

**Comment by infusion** [comment]
You're right, the condition was too restrictive. I made it work for full `a`. I was wondering if excluding the case `0^0` should be avoided here, but the result should behave somehow similar to the JS specs. THX for bringing this up. The new version is on npm
