### ISSUE TITLE
Ship Type Definitions

### ISSUE THREAD

**Issue by stefnotch** [infusion/Complex.js#35]
This library is really well made, thank you for all your hard work!

Since most packages on npm have Typescript definitions, I wanted to ask whether that would be welcome here as well. As I understand it, simply adopting ES modules and adding Typescript and might not be the best option. After all, this library tries to [keep its size down to a minimum](https://github.com/infusion/Complex.js#coding-style).

I'd love to add Typescript definitions, in whatever form you think would be best.

**Comment by infusion** [comment]
With fraction.js we have type definitions already: https://github.com/infusion/Fraction.js/blob/master/fraction.d.ts

You're more than welcome to add a type definition file for complex.js in a similar way!
