### ISSUE TITLE
exp() error in result

### ISSUE THREAD

**Issue by PaulEdouardB** [infusion/Complex.js#43]
Complex({re: a, im: b}).exp() should return exp(a)exp(ib) with exp(ib) = [cos(b), i sin(b)] but for now it computes only the exp(ib) part and not the exp(a) part. 
To get the right answer I had to do that : Complex({re: 0, im: b}).exp().mul(a)

**Comment by infusion** [comment]
I don't quite understand what you mean. These three expressions are equal:

```
    var t1 = Complex({re: a, im: b}).exp();
    var t2 = Complex(a).exp().mul(Complex.I.mul(b).exp());
    var t3 = Complex(a).exp().mul(Complex({re:0, im: b}).exp());
```

**Comment by PaulEdouardB** [comment]
Oh I understand my mistake, my bad.
